# Print the github context

name: Debug GitHub Context

on:
  push:
    tags:
      - "v*"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: Print GitHub context
        run: |
          echo "GITHUB_CONTEXT: ${{ toJson(github) }}"
          echo "GITHUB_REF: ${{ github.ref }}"
          echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
          echo "GITHUB_SHA: ${{ github.sha }}"
          echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
          echo "GITHUB_EVENT_PATH: ${{ github.event_path }}"
          echo "GITHUB_WORKFLOW: ${{ github.workflow }}"
          echo "GITHUB_WORKSPACE: ${{ github.workspace }}"
